### ISSUE TITLE
Unable to deploy twice with FTP (engine = jsftp)

### ISSUE THREAD

**Issue by steph643** [mkloubert/vscode-deploy-reloaded#45]
This issue only occurs with `engine` == `jsftp`.

I can deploy a file on an "empty" FTP without any problem: the `dir` folder is created automatically and the file is uploaded. However, if I try to deploy the file a second time, I get this error:
```
Deploying file 'c:\Users\Sylvain\Travail\Projets en cours\Docuss\r&d - docuss-demo\docuss-demo\index.html' to '/ (docuss.free.fr)' ... [ERROR: 'Unexpected command 227 Entering Passive Mode (212,27,63,108,217,111).']
```
If I remove the file on the ftp server (but not the folder) and try to deploy again, deployment gets stuck to:
```
Deploying file 'c:\Users\Sylvain\Travail\Projets en cours\Docuss\r&d - docuss-demo\docuss-demo\index.html' to '/ (docuss.free.fr)' ...
```
Only if I delete the `dir` folder entirely can I upload again and get the success message:
```
Deploying file 'c:\Users\Sylvain\Travail\Projets en cours\Docuss\r&d - docuss-demo\docuss-demo\index.html' to '/ (docuss.free.fr)' ... [OK]
```

As a corollary, I am not able to deploy to the root of my ftp server, probably because the root folder is always there and cannot be removed. So anything like  `dir` == `"/"` or `dir` == `""` or no `dir` at all in settings.json leads to the first error above.

**Comment by mkloubert** [comment]
@steph643 

Any of the engines should be able to create directories automatically.

There was an issue when trying to list the root directory, to check if a directory needs to be created.

**The bug should be fixed since version 0.62.3.**

**Comment by steph643** [comment]
It seems the issue is still there. I'm using 0.62.3.

Maybe there's something special with my FTP server (it's my ISP's FTP server, known to be unreliable), but I've tried with another extension ([ftp-kr](https://github.com/karikera/ftp-kr)) and it works well.
